// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUkzIUUnJvx1CCOkR6YGkhenQMP4Gwkd0',
    appId: '1:689422214219:web:cad2d93c43b60fdd7419ce',
    messagingSenderId: '689422214219',
    projectId: 'zibene-f72fa',
    authDomain: 'zibene-f72fa.firebaseapp.com',
    storageBucket: 'zibene-f72fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdKY2fXvICoaqlzzi2OrnOUm4bzfEVMIY',
    appId: '1:689422214219:android:3e993f19ffe4cfab7419ce',
    messagingSenderId: '689422214219',
    projectId: 'zibene-f72fa',
    storageBucket: 'zibene-f72fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEYnl4VQ5SWNOyafJ7LmIcTt3BAj8sh2A',
    appId: '1:689422214219:ios:f35114b9478547137419ce',
    messagingSenderId: '689422214219',
    projectId: 'zibene-f72fa',
    storageBucket: 'zibene-f72fa.firebasestorage.app',
    iosBundleId: 'com.example.beeApp',
  );
}
